name: Deploy to Inleed

on:
  push:
    branches:
      - main
      - develop
      - test1
      - test2
  workflow_dispatch:

env:
  NODE_VERSION: '24'
  SERVER_NODE_VERSION: '18'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Create deployment package
        run: |
          tar -czf app.tar.gz build package.json package-lock.json _passenger.cjs

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: release-package
          path: app.tar.gz

  deploy-dev:
    if: |
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/test1' ||
      github.ref == 'refs/heads/test2'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set environment
        id: env
        run: |
          if [ "${{ github.ref }}" = 'refs/heads/develop' ]; then
            echo "APP_ROOT=${{ secrets.APP_ROOT_DEVELOPMENT }}" >> "$GITHUB_ENV"
            echo "DOMAIN=${{ secrets.DOMAIN_DEVELOPMENT }}" >> "$GITHUB_ENV"
          elif [ "${{ github.ref }}" = 'refs/heads/test1' ]; then
            echo "APP_ROOT=${{ secrets.APP_ROOT_TEST1 }}" >> "$GITHUB_ENV"
            echo "DOMAIN=${{ secrets.DOMAIN_TEST1 }}" >> "$GITHUB_ENV"
          elif [ "${{ github.ref }}" = 'refs/heads/test2' ]; then
            echo "APP_ROOT=${{ secrets.APP_ROOT_TEST2 }}" >> "$GITHUB_ENV"
            echo "DOMAIN=${{ secrets.DOMAIN_TEST2 }}" >> "$GITHUB_ENV"
          else
            exit 1
          fi

      - name: Stop app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cloudlinux-selector stop --json \
              --interpreter nodejs \
              --app-root "${{env.APP_ROOT}}"

      - name: Download artifact from build job
        uses: actions/download-artifact@v7
        with:
          name: release-package

      - name: Upload files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'app.tar.gz'
          target: '${{ env.APP_ROOT }}'

      - name: Install + start app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd "${{env.APP_ROOT}}"

            rm -rf build
            tar -xzf app.tar.gz
            rm app.tar.gz

            # Activate the Node environment provided by Inleed (DirectAdmin and cPanel)
            source /home/${{ secrets.SSH_USER }}/nodevenv/${{env.APP_ROOT}}/${{env.SERVER_NODE_VERSION}}/bin/activate || true
            npm install --omit=dev

            cloudlinux-selector start --json \
              --interpreter nodejs \
              --app-root "${{env.APP_ROOT}}"

  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Stop app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST_MAIN }}
          port: ${{ secrets.SSH_PORT_MAIN }}
          username: ${{ secrets.SSH_USER_MAIN }}
          key: ${{ secrets.SSH_PRIVATE_KEY_MAIN }}
          script: |
            cloudlinux-selector stop --json \
              --interpreter nodejs \
              --app-root "${{ secrets.APP_ROOT_MAIN }}"

      - name: Download artifact from build job
        uses: actions/download-artifact@v7
        with:
          name: release-package

      - name: Upload files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST_MAIN }}
          port: ${{ secrets.SSH_PORT_MAIN }}
          username: ${{ secrets.SSH_USER_MAIN }}
          key: ${{ secrets.SSH_PRIVATE_KEY_MAIN }}
          source: 'app.tar.gz'
          target: '${{ secrets.APP_ROOT_MAIN }}'

      - name: Install + start app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST_MAIN }}
          port: ${{ secrets.SSH_PORT_MAIN }}
          username: ${{ secrets.SSH_USER_MAIN }}
          key: ${{ secrets.SSH_PRIVATE_KEY_MAIN }}
          script: |
            cd "${{secrets.APP_ROOT_MAIN}}"

            rm -rf build
            tar -xzf app.tar.gz
            rm app.tar.gz

            # Activate the Node environment provided by Inleed (DirectAdmin and cPanel)
            source /home/${{ secrets.SSH_USER_MAIN }}/nodevenv/${{secrets.APP_ROOT_MAIN}}/${{env.SERVER_NODE_VERSION}}/bin/activate || true
            npm install --omit=dev

            cloudlinux-selector start --json \
              --interpreter nodejs \
              --app-root "${{secrets.APP_ROOT_MAIN}}"
