name: Deploy to Inleed

on:
  push:
    branches:
      - main
      - test1
  workflow_dispatch:

env:
  NODE_VERSION: '24'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Create deployment package
        run: |
          tar -czf app.tar.gz build package.json package-lock.json

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: release-package
          path: app.tar.gz

  deploy:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - name: Set environment
        id: env
        run: |
          if [ "${{ github.ref }}" = 'refs/heads/main' ]; then
            echo "APP_ROOT=${{ secrets.APP_ROOT_MAIN }}" >> "$GITHUB_ENV"
            echo "DOMAIN=${{ secrets.DOMAIN_MAIN }}" >> "$GITHUB_ENV"
          elif [ "${{ github.ref }}" = 'refs/heads/test1' ]; then
            echo "APP_ROOT=${{ secrets.APP_ROOT_TEST1 }}" >> "$GITHUB_ENV"
            echo "DOMAIN=${{ secrets.DOMAIN_TEST1 }}" >> "$GITHUB_ENV"
          else
            exit 1
          fi

      - name: Stop app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cloudlinux-selector stop --json \
              --interpreter nodejs \
              --app-root ${{env.APP_ROOT}}

      - name: Download artifact from build job
        uses: actions/download-artifact@v7
        with:
          name: release-package

      - name: Upload files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.tar.gz"
          target: "${{ env.APP_ROOT }}"
          debug: true

      - name: Install + start app
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{env.APP_ROOT}}

            rm -r build
            tar -xzf app.tar.gz
            rm app.tar.gz

            # ensure correct environment (adjust if Inleed requires sourcing)
            source /home/${{ secrets.SSH_USER }}/nodevenv/${APP_ROOT}/18/bin/activate || true

            npm install --omit=dev

            cloudlinux-selector start --json \
              --interpreter nodejs \
              --app-root ${{env.APP_ROOT}}